
# Read about DVC pipeline configuration (https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#stages)
# to customize your stages even more
stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py