preprocess:
  seed: 2
  var_threshold: 0.9
  umap:
    n_neighbors: 10
    n_components: 3
    min_dist: 0.2

silhouette:
  seed: 2
  metric: "euclidean"
  range_x: 2
  range_y: 5

davies_bouldin:
  seed: 2
  range_x: 2
  range_y: 15

kmeans:
  seed: 2
  silhouette_k: True
  davies_bouldin_k: False
  default_k: 5

dbscan:
  seed: 2
  epsilon: 0.15
  min_samples: 3